### ISSUE TITLE
"Empty" ExchangePointRequest from 5T

### ISSUE THREAD

**Issue by ue71603** [LinkingAlps/Main#15]
According to the specification a simple EPR should provide all results

Request
`<?xml version="1.0" encoding="UTF-8"?>
<siri:OJP xmlns:siri="http://www.siri.org.uk/siri"
          xmlns:ojp="http://www.vdv.de/ojp"
          version="1.0">
    <siri:OJPRequest>
        <siri:ServiceRequest>
            <siri:RequestTimestamp>2021-04-21T15:20:35Z</siri:RequestTimestamp>
            <siri:RequestorRef>EFALocationCollector10.5.0.0-STR-DB-20</siri:RequestorRef>
            <siri:MessageIdentifier>A58C62B8-3E89-48F9-AECC-FD09CF155AE4</siri:MessageIdentifier>
            <ojp:OJPExchangePointsRequest>
                <siri:RequestTimestamp>2021-04-21T15:20:35Z</siri:RequestTimestamp>
                <ojp:Params>
                    <ojp:NumberOfResults>500</ojp:NumberOfResults>
                    <ojp:ContinueAt>0</ojp:ContinueAt>
                </ojp:Params>
            </ojp:OJPExchangePointsRequest>
        </siri:ServiceRequest>
    </siri:OJPRequest>
</siri:OJP>
`
The response however is:
`<?xml version="1.0" encoding="utf-8"?>
<siri:OJP xmlns:siri="http://www.siri.org.uk/siri" xmlns:ojp="http://www.vdv.de/ojp" version="1.0">
    <siri:OJPResponse>
        <siri:ServiceDelivery>
            <siri:ResponseTimestamp>2021-08-19T12:13:36.352Z</siri:ResponseTimestamp>
            <siri:ProducerRef>OJP OpenMove Middleware</siri:ProducerRef>
            <siri:Status>true</siri:Status>
            <ojp:OJPExchangePointsDelivery>
                <siri:ResponseTimestamp>2021-08-19T12:13:36.353Z</siri:ResponseTimestamp>
                <siri:Status>false</siri:Status>
                <ojp:CalcTime>1</ojp:CalcTime>
                <siri:ErrorCondition>
                    <siri:OtherError/>
                    <siri:Description>E0001</siri:Description>
                </siri:ErrorCondition>
            </ojp:OJPExchangePointsDelivery>
        </siri:ServiceDelivery>
    </siri:OJPResponse>
</siri:OJP>
`

**Comment by roby2107** [comment]
Now provides all results (for now limited to 5T EPs). 
Closing

**Comment by ue71603** [comment]
Better but there are still issues:
URL = https://www.muoversinpiemonte.it/ojp

`
<?xml` version="1.0" encoding="UTF-8"?>
<siri:OJP xmlns:siri="http://www.siri.org.uk/siri"
          xmlns:ojp="http://www.vdv.de/ojp"
          version="1.0">
    <siri:OJPRequest>
        <siri:ServiceRequest>
            <siri:RequestTimestamp>2021-04-21T15:20:35Z</siri:RequestTimestamp>
            <siri:RequestorRef>EFALocationCollector10.5.0.0-STR-DB-20</siri:RequestorRef>
            <siri:MessageIdentifier>A58C62B8-3E89-48F9-AECC-FD09CF155AE4</siri:MessageIdentifier>
            <ojp:OJPExchangePointsRequest>
                <siri:RequestTimestamp>2021-04-21T15:20:35Z</siri:RequestTimestamp>
            </ojp:OJPExchangePointsRequest>
        </siri:ServiceRequest>
    </siri:OJPRequest>
</siri:OJP>
`
delivers

line 15:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST00108290038:</ojp:StopPlaceRef>
line 35:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0012729010:</ojp:StopPlaceRef>
line 55:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0012729012:</ojp:StopPlaceRef>
line 75:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0012729029:</ojp:StopPlaceRef>
line 95:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0021339001:</ojp:StopPlaceRef>

`<?xml version="1.0" encoding="UTF-8"?>
<siri:OJP xmlns:siri="http://www.siri.org.uk/siri"
          xmlns:ojp="http://www.vdv.de/ojp"
          version="1.0">
    <siri:OJPRequest>
        <siri:ServiceRequest>
            <siri:RequestTimestamp>2021-04-21T15:20:35Z</siri:RequestTimestamp>
            <siri:RequestorRef>EFALocationCollector10.5.0.0-STR-DB-20</siri:RequestorRef>
            <siri:MessageIdentifier>A58C62B8-3E89-48F9-AECC-FD09CF155AE4</siri:MessageIdentifier>
            <ojp:OJPExchangePointsRequest>
                <siri:RequestTimestamp>2021-04-21T15:20:35Z</siri:RequestTimestamp>
                <ojp:Params>
                    <ojp:NumberOfResults>500</ojp:NumberOfResults>
                    <ojp:ContinueAt>0</ojp:ContinueAt>
                </ojp:Params>
            </ojp:OJPExchangePointsRequest>
        </siri:ServiceRequest>
    </siri:OJPRequest>
</siri:OJP>`
delivers

line 15:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST00108290038:</ojp:StopPlaceRef>
line 35:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0012729010:</ojp:StopPlaceRef>
line 55:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0012729012:</ojp:StopPlaceRef>
line 75:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0012729029:</ojp:StopPlaceRef>
line 95:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0021339001:</ojp:StopPlaceRef>
line 115:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0021589002:</ojp:StopPlaceRef>
line 135:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0031069001:</ojp:StopPlaceRef>
line 155:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0050059001:</ojp:StopPlaceRef>
line 175:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST0060039003:</ojp:StopPlaceRef>
line 195:                             <ojp:StopPlaceRef>it:itc:StopPlace:ITRP-ST1030289001:</ojp:StopPlaceRef>

**Comment by ue71603** [comment]
<OJPRequest>
        <ServiceRequest>
            <RequestTimestamp>2020-05-07T12:00:00Z</RequestTimestamp>
            <RequestorRef>IRMA</RequestorRef>
            <ojp:OJPLocationInformationRequest>
                <RequestTimestamp>2020-05-07T12:00:00Z</RequestTimestamp>
                <MessageIdentifier>4711</MessageIdentifier>
                <ojp:InitialInput>
                    <ojp:LocationName></ojp:LocationName>
                </ojp:InitialInput>
                <ojp:Restrictions>
                    <ojp:Type>stop</ojp:Type>
                </ojp:Restrictions>
            </ojp:OJPLocationInformationRequest>
        </ServiceRequest>
    </OJPRequest>
</OJP>

still delivers
` <?xml version="1.0" encoding="utf-8"?>
<siri:OJP xmlns:siri="http://www.siri.org.uk/siri" xmlns:ojp="http://www.vdv.de/ojp" version="1.0">
    <siri:OJPResponse>
        <siri:ServiceDelivery>
            <siri:ResponseTimestamp>2021-09-14T10:28:06.096Z</siri:ResponseTimestamp>
            <siri:ProducerRef>OJP OpenMove Middleware</siri:ProducerRef>
            <siri:Status>true</siri:Status>
            <ojp:OJPLocationInformationDelivery>
                <siri:ResponseTimestamp>2021-09-14T10:28:06.127Z</siri:ResponseTimestamp>
                <siri:Status>false</siri:Status>
                <ojp:CalcTime>31</ojp:CalcTime>
                <siri:ErrorCondition>
                    <siri:OtherError/>
                    <siri:Description>LOCATION_NORESULTS</siri:Description>
                </siri:ErrorCondition>
            </ojp:OJPLocationInformationDelivery>
        </siri:ServiceDelivery>
    </siri:OJPResponse>
</siri:OJP>
`

**Comment by roby2107** [comment]
New API version released: please, try it now @ue71603

**Comment by roby2107** [comment]
API updated. Closing
