### ISSUE TITLE
OJPLocationInformationRequest with empty Location Name should send all stops

### ISSUE THREAD

**Issue by ue71603** [LinkingAlps/Main#17]
A ojp:OJPLocationInformationRequest with empty LocationName should send all stops and not an error in our opinion.

**The Request** 
<?xml version="1.0" encoding="UTF-8"?>
<OJP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.siri.org.uk/siri" version="1.0" xmlns:ojp="http://www.vdv.de/ojp" xsi:schemaLocation="http://www.siri.org.uk/siri ../ojp-xsd-v1.0/OJP.xsd">
    <OJPRequest>
        <ServiceRequest>
            <RequestTimestamp>2020-05-07T12:00:00Z</RequestTimestamp>
            <RequestorRef>IRMA</RequestorRef>
            <ojp:OJPLocationInformationRequest>
                <RequestTimestamp>2020-05-07T12:00:00Z</RequestTimestamp>
                <MessageIdentifier>4711</MessageIdentifier>
                <ojp:InitialInput>
                    <ojp:LocationName></ojp:LocationName>
                </ojp:InitialInput>
                <ojp:Restrictions>
                    <ojp:Type>stop</ojp:Type>
                </ojp:Restrictions>
            </ojp:OJPLocationInformationRequest>
        </ServiceRequest>
    </OJPRequest>
</OJP>

**Results in**
------------------------------------------------------------------------
<html>

<body>
    <h1>504 Gateway Time-out</h1>
    The server didn't respond in time.
</body>

</html>
------------------------------------------------------------------------

**Correct behaviour**
It should however send all stops

**Comment by roby2107** [comment]
New release available. Closing
